Property Management/Controllers/AdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Property_Management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Property_Management.Controllers
{   //[Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AdminController()
        {
        }

        public AdminController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
  
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            
            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:                   
                    return RedirectToLocal("/Home/Index");
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        [AllowAnonymous]
        // GET: /Account/Register
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View(db.Users.ToList());
        }
        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }


       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }

                if (_signInManager != null)
                {
                    _signInManager.Dispose();
                    _signInManager = null;
                }
            }

            base.Dispose(disposing);
        }
        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }
        #endregion

    }
}

Property Management/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Property_Management.Models;
using System.Collections;

namespace Property_Management.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult NewsList(int? id)
        {
            if (id == null)
            { 
            return View(db.News.OrderByDescending(x => x.CreatedOn).ToList());
            }

            IEnumerable news = db.News.Where(x=> x.NewsId == id).ToList();
            if (news ==null)
            {
                //Redirect to no such page found error page
                return HttpNotFound();
            }
            return View(news);

        }

        public ActionResult FeaturedNews()
        {
            var featured = db.News.Where(x => x.IsFeatured == true).ToList();
            return View(featured);
        }
        // GET: News
        public ActionResult Index()
        {
           
            return View(db.News.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(News news)
        {
            if (ModelState.IsValid)
            {

                string previewString = String.Format("{0}...", news.Content.ToString().Substring(0, 140));

                news.CreatedOn = DateTime.Now;
                news.Preview = previewString;
                db.News.Add(news);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(news);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //or redirect to no such page 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditNewsViewModel news)
        {
            if (ModelState.IsValid)
            {
                var oldNews = db.News.Find(news.NewsId);

                oldNews.Title = news.Title;
                oldNews.Content = news.Content;
                oldNews.IsFeatured = news.IsFeatured;
                oldNews.Preview = string.Format("{0}...", news.Content.ToString().Substring(0, 1));

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Property Management/Views/Admin/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<div class="container ">
    <div class="row">
        <div class="col-sm-8 col-sm-push-2 margin-top-bottom">
            <h2 class="">Welcome to the admin section of the website</h2>
            <h3> What would you like to do</h3>
            <div class="col-md-8">

                <div> 
                    <p>have to check what happens when user is registerded- not to log him.Also to add log-out button. Find out how it works with User CRUD</p> 
                    @Html.ActionLink("Register New User", "Register")
                </div>

                <div>
                    @Html.ActionLink("Manage News","Index","News")
                </div>
                

            </div>


        </div>
    </div>

</div>



Property Management/Views/Admin/Login.cshtml
@using Property_Management.Models
@model LoginViewModel

@*    -----------CHECK THIS - RE
    <p>
        @Html.ActionLink("Register as a new user", "Register")
    </p>

    @* Enable this once you have account confirmation enabled for password reset functionality
        <p>
            @Html.ActionLink("Forgot your password?", "ForgotPassword")
        </p>
*@




<div class="container">
    <div class="row">


        <div class="margin-top-bottom text-center">
            <h2>Welcome back, Adelina!</h2>
            <h3>Please log in</h3>
        </div>
        @using (Html.BeginForm("Login", "Admin", FormMethod.Post, new { @class = "col-sm-6 col-sm-push-3" })) 
        {
            @Html.AntiForgeryToken();


            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div>
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">

                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                <div>
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(m => m.RememberMe)
                        @Html.LabelFor(m => m.RememberMe)
                    </div>
                </div>
            </div>
            <div class="form-group margin-bottom">
                <div>
                    <input type="submit" value="Agent Log in" class="btn btn-default" />
                </div>
            </div>
        }

    </div>
</div>

        
       
       

  
 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Property Management/Views/Admin/Register.cshtml
@model Property_Management.Models.RegisterViewModel


<div class="container margin-bottom">
    <div class="row margin-top-bottom">

        <h2 class="margin-top-bottom"> Create new user account</h2>
        @Html.ActionLink("Back to Admin Home Page", "Index", "Admin", routeValues: null, htmlAttributes: new { @class = "text-center" })


        @using (Html.BeginForm("Register", "Admin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 col-sm-push-1 control-label" })
                <div class="col-sm-6 col-sm-push-1">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-sm-2 col-sm-push-1 control-label" })
                <div class="col-sm-6 col-sm-push-1">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-sm-2 col-sm-push-1 control-label" })
                <div class="col-sm-6 col-sm-push-1">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-sm-10">
                    <input type="submit" class="btn btn-default" value="Register" />
                </div>
            </div>
        }


    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}